### ISSUE TITLE
scrlayer2 package obsolete

### ISSUE THREAD

**Issue by psanan** [egoat/I3ELVIS-guide#2]
I had to replace 

    \usepackage{scrpage2}

with

    \usepackage{scrlayer-scrpage}

to be able to build `I3ELVIS_main.tex`. I don't know what this package does, but [the TeX Stackexchange](https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found/541772) suggested the above change. If that seems reasonable, you could update. (There is the larger issue that most people seem to have invest more than trivial effort to be able to build LaTeX locally, so most will never do it. That justifies horrible things like just checking a PDF into a repo like this, so people have something to click on.. )

**Comment by egoat** [comment]
The package is changed from _scrpage2_ to _scrlayer-scrpage_.
I have also added the PDF for convenience.
